version: "2.1"
services:

  api:
    environment:
      - NODE_ENV=production
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - QUORUM_INIT_HOST=${QUORUM_INIT_HOST}
      # Provide the nodeId:rpcPort pairs of all nodes running with current docker-compose.yml
      - QUORUM_INIT_RPC_PORTS=1:22001,2:22002,3:22003
      - QUORUM_INIT_CONSTELLATION_PORTS=1:9000,2:9001,3:9002
    image: nd-api
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - postgres

  ui:
    environment:
      - HOST_NAME=${HOST_NAME}
    image: nd-ui
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - api

  postgres:
    environment:
      - POSTGRES_DB=governance_prod
      - POSTGRES_USER=postgres
    image: postgres:9.6
    # Do not open the port on production machine if PGPASSWORD is not set
    ports:
      - 5432:5432

  nginx:
    depends_on:
      - api
      - ui
    restart: always
    image: nginx:stable-alpine
    ports:
      - 80:80
#      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./certs/server.pem:/etc/ssl/certs/server.pem:ro \
#      - ./certs/server.key:/etc/ssl/private/server.key:ro \

  node1:
    environment:
      - nodeId=1
      - HOST_IP=${HOST_IP}
    image: repo.blockapps.net:5000/blockapps-repo/quorum-node
    ports:
      - 21001:21001
      - 21001:21001/udp
      - 22001:22001
      - 54001:54001
      - 9000:9000
    restart: always
    volumes:
      - ./api/quorum-config:/root/config/:ro

  node2:
    environment:
      - nodeId=2
      - HOST_IP=${HOST_IP}
    image: repo.blockapps.net:5000/blockapps-repo/quorum-node
    ports:
      - 21002:21002
      - 21002:21002/udp
      - 22002:22002
      - 54002:54002
      - 9001:9001
    restart: always
    volumes:
      - ./api/quorum-config:/root/config/:ro

  node3:
    environment:
      - nodeId=3
      - HOST_IP=${HOST_IP}
    image: repo.blockapps.net:5000/blockapps-repo/quorum-node
    ports:
      - 21003:21003
      - 21003:21003/udp
      - 22003:22003
      - 54003:54003
      - 9002:9002
    restart: always
    volumes:
      - ./api/quorum-config:/root/config/:ro